# Generated by Django 6.0.7 on 2026-09-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                default="draft",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
